# Universo inicial de ações da Zona Euro para o InvestScore.
#
# Cobertura: principais índices nacionais da Zona Euro —
# PSI20 (Portugal), CAC40 (França), DAX40 (Alemanha), IBEX35 (Espanha),
# AEX25 (Países Baixos), BEL20 (Bélgica) e FTSE MIB (Itália).
#
# Todos os tickers usam o sufixo de bolsa reconhecido pelo Yahoo Finance
# (.LS Lisboa, .PA Paris, .DE Frankfurt/Xetra, .MC Madrid, .AS Amesterdão,
# .BR Bruxelas, .MI Milão).
#
# AVISO IMPORTANTE:
# Esta lista foi construída com base em conhecimento geral de mercado e
# pesquisa pontual (não uma verificação linha-a-linha de cada ticker via
# fonte oficial de cada bolsa). Composições de índices mudam ao longo do
# tempo (entradas, saídas, fusões, mudanças de sufixo). Antes de usar isto
# em produção/cobrar por isto, vale a pena validar a lista contra uma fonte
# oficial (Euronext, Deutsche Börse, BME, Borsa Italiana) pelo menos uma vez.

tickers = [
    # --- Portugal (PSI20) ---
    "EDP.LS",
    "EDPR.LS",
    "GALP.LS",
    "JMT.LS",
    "BCP.LS",
    "SON.LS",
    "NOS.LS",
    "RENE.LS",
    "NVG.LS",
    "SEM.LS",
    "EGL.LS",
    "ALTR.LS",
    "COR.LS",
    "IBS.LS",
    "CTT.LS",
    "GLINT.LS",
    "NBA.LS",
    "RAM.LS",

    # --- França (CAC40) ---
    "MC.PA",
    "TTE.PA",
    "SAN.PA",
    "OR.PA",
    "AIR.PA",
    "SU.PA",
    "BNP.PA",
    "CS.PA",
    "AI.PA",
    "DG.PA",
    "KER.PA",
    "BN.PA",
    "SGO.PA",
    "EL.PA",
    "RMS.PA",
    "ML.PA",
    "ORA.PA",
    "ACA.PA",
    "GLE.PA",
    "PUB.PA",
    "RNO.PA",
    "CAP.PA",
    "LR.PA",
    "DSY.PA",
    "EN.PA",
    "CA.PA",
    "VIE.PA",
    "ENGI.PA",
    "SAF.PA",
    "HO.PA",
    "RI.PA",
    "STMPA.PA",
    "ERF.PA",
    "URW.PA",
    "EDEN.PA",
    "AC.PA",
    "MT.AS",
    "BVI.PA",
    "STLAP.PA",
    "TEP.PA",

    # --- Alemanha (DAX40) ---
    "SAP.DE",
    "SIE.DE",
    "ALV.DE",
    "DTE.DE",
    "MBG.DE",
    "BMW.DE",
    "VOW3.DE",
    "BAS.DE",
    "BAYN.DE",
    "SHL.DE",
    "DBK.DE",
    "MUV2.DE",
    "ADS.DE",
    "DB1.DE",
    "IFX.DE",
    "RWE.DE",
    "EOAN.DE",
    "DHL.DE",
    "CON.DE",
    "HEN3.DE",
    "FRE.DE",
    "FME.DE",
    "MRK.DE",
    "VNA.DE",
    "ZAL.DE",
    "BEI.DE",
    "SY1.DE",
    "HNR1.DE",
    "CBK.DE",
    "HEI.DE",
    "BNR.DE",
    "RHM.DE",
    "SRT3.DE",
    "MTX.DE",
    "QIA.DE",
    "DTG.DE",
    "P911.DE",
    "PAH3.DE",
    "ENR.DE",

    # --- Espanha (IBEX35) ---
    "SAN.MC",
    "BBVA.MC",
    "ITX.MC",
    "IBE.MC",
    "REP.MC",
    "TEF.MC",
    "CABK.MC",
    "AMS.MC",
    "NTGY.MC",
    "ELE.MC",
    "ACS.MC",
    "AENA.MC",
    "GRF.MC",
    "MAP.MC",
    "BKT.MC",
    "RED.MC",
    "ANA.MC",
    "COL.MC",
    "MRL.MC",
    "FDR.MC",
    "CLNX.MC",
    "IAG.MC",
    "SAB.MC",
    "ENG.MC",
    "SLR.MC",
    "IDR.MC",
    "ACX.MC",
    "LOG.MC",
    "PUIG.MC",
    "UNI.MC",
    "FER.MC",
    "ROVI.MC",
    "SCYR.MC",

    # --- Países Baixos (AEX25) ---
    "ASML.AS",
    "SHELL.AS",
    "HEIA.AS",
    "PHIA.AS",
    "INGA.AS",
    "AD.AS",
    "ADYEN.AS",
    "WKL.AS",
    "RAND.AS",
    "DSFIR.AS",
    "PRX.AS",
    "ASM.AS",
    "NN.AS",
    "AGN.AS",
    "KPN.AS",
    "AKZA.AS",
    "LIGHT.AS",
    "IMCD.AS",
    "UMG.AS",
    "BFIT.AS",
    "UNA.AS",
    "REN.AS",
    "ABN.AS",
    "BESI.AS",

    # --- Bélgica (BEL20) ---
    "ABI.BR",
    "KBC.BR",
    "UCB.BR",
    "SOLB.BR",
    "SYENS.BR",
    "AGS.BR",
    "COLR.BR",
    "ELI.BR",
    "PROX.BR",
    "UMI.BR",
    "GBLB.BR",
    "SOF.BR",
    "COFB.BR",
    "ARGX.BR",
    "MELE.BR",
    "WDP.BR",
    "AZE.BR",
    "ACKB.BR",
    "LOTB.BR",
    "DIE.BR",
    "APAM.AS",

    # --- Itália (FTSE MIB) ---
    "ENEL.MI",
    "ENI.MI",
    "ISP.MI",
    "UCG.MI",
    "RACE.MI",
    "G.MI",
    "TRN.MI",
    "SRG.MI",
    "PST.MI",
    "MONC.MI",
    "PRY.MI",
    "LDO.MI",
    "REC.MI",
    "CPR.MI",
    "BAMI.MI",
    "MB.MI",
    "NEXI.MI",
    "AMP.MI",
    "IP.MI",
    "DIA.MI",
    "INW.MI",
    "TEN.MI",
    "TIT.MI",
    "SPM.MI",
    "BPE.MI",
    "FBK.MI",
    "IVG.MI",
    "PIRC.MI",
    "BMED.MI",
    "AZM.MI",
    "HER.MI",
    "A2A.MI",
    "IG.MI",
]
