from tickers_eurozone import tickers


_VALID_TICKERS = set(tickers)


_setores_base = {
    "Bancos e Serviços Financeiros": [
        "BCP.LS",
        "BNP.PA",
        "CS.PA",
        "ACA.PA",
        "GLE.PA",
        "ALV.DE",
        "DBK.DE",
        "MUV2.DE",
        "DB1.DE",
        "HNR1.DE",
        "CBK.DE",
        "SAN.MC",
        "BBVA.MC",
        "CABK.MC",
        "MAP.MC",
        "BKT.MC",
        "SAB.MC",
        "UNI.MC",
        "INGA.AS",
        "NN.AS",
        "AGN.AS",
        "KBC.BR",
        "AGS.BR",
        "GBLB.BR",
        "SOF.BR",
        "ACKB.BR",
        "PAH3.DE",
        "ABN.AS",
        "ISP.MI",
        "UCG.MI",
        "G.MI",
        "PST.MI",
        "BAMI.MI",
        "MB.MI",
        "BPE.MI",
        "FBK.MI",
        "BMED.MI",
        "AZM.MI",
    ],
    "Energia e Utilities": [
        "EDP.LS",
        "EDPR.LS",
        "RENE.LS",
        "VIE.PA",
        "ENGI.PA",
        "RWE.DE",
        "EOAN.DE",
        "ENR.DE",
        "IBE.MC",
        "NTGY.MC",
        "ELE.MC",
        "RED.MC",
        "ANA.MC",
        "ENG.MC",
        "SLR.MC",
        "ELI.BR",
        "ENEL.MI",
        "TRN.MI",
        "SRG.MI",
        "HER.MI",
        "A2A.MI",
        "IG.MI",
    ],
    "Petróleo, Gás e Químicos": [
        "GALP.LS",
        "TTE.PA",
        "REP.MC",
        "SHELL.AS",
        "ENI.MI",
        "SPM.MI",
    ],
    "Materiais e Química": [
        "NVG.LS",
        "SEM.LS",
        "ALTR.LS",
        "COR.LS",
        "RAM.LS",
        "AI.PA",
        "SGO.PA",
        "BAS.DE",
        "SY1.DE",
        "HEI.DE",
        "BNR.DE",
        "ACX.MC",
        "DSFIR.AS",
        "AKZA.AS",
        "IMCD.AS",
        "SOLB.BR",
        "SYENS.BR",
        "UMI.BR",
        "AZE.BR",
        "TEN.MI",
        "MT.AS",
        "APAM.AS",
    ],
    "Consumo e Varejo": [
        "JMT.LS",
        "SON.LS",
        "IBS.LS",
        "BN.PA",
        "CA.PA",
        "RI.PA",
        "ADS.DE",
        "HEN3.DE",
        "BEI.DE",
        "ZAL.DE",
        "ITX.MC",
        "HEIA.AS",
        "AD.AS",
        "BFIT.AS",
        "ABI.BR",
        "COLR.BR",
        "CPR.MI",
        "AC.PA",
        "UNA.AS",
        "LOTB.BR",
    ],
    "Luxo e Bens Premium": [
        "MC.PA",
        "OR.PA",
        "KER.PA",
        "EL.PA",
        "RMS.PA",
        "PUIG.MC",
        "RACE.MI",
        "MONC.MI",
    ],
    "Saúde e Farmacêutica": [
        "SAN.PA",
        "BAYN.DE",
        "SHL.DE",
        "FRE.DE",
        "FME.DE",
        "MRK.DE",
        "SRT3.DE",
        "QIA.DE",
        "GRF.MC",
        "PHIA.AS",
        "UCB.BR",
        "ARGX.BR",
        "REC.MI",
        "AMP.MI",
        "DIA.MI",
        "ERF.PA",
        "ROVI.MC",
    ],
    "Indústria e Transporte": [
        "EGL.LS",
        "CTT.LS",
        "AIR.PA",
        "SU.PA",
        "DG.PA",
        "ML.PA",
        "RNO.PA",
        "LR.PA",
        "EN.PA",
        "SAF.PA",
        "HO.PA",
        "SIE.DE",
        "MBG.DE",
        "BMW.DE",
        "VOW3.DE",
        "DHL.DE",
        "CON.DE",
        "RHM.DE",
        "MTX.DE",
        "ACS.MC",
        "AENA.MC",
        "BVI.PA",
        "FDR.MC",
        "IAG.MC",
        "LOG.MC",
        "RAND.AS",
        "LIGHT.AS",
        "STLAP.PA",
        "PRY.MI",
        "LDO.MI",
        "IP.MI",
        "IVG.MI",
        "PIRC.MI",
        "DTG.DE",
        "P911.DE",
        "FER.MC",
        "SCYR.MC",
        "DIE.BR",
    ],
    "Tecnologia e Telecom": [
        "NOS.LS",
        "GLINT.LS",
        "NBA.LS",
        "ORA.PA",
        "PUB.PA",
        "CAP.PA",
        "DSY.PA",
        "STMPA.PA",
        "EDEN.PA",
        "SAP.DE",
        "DTE.DE",
        "IFX.DE",
        "TEF.MC",
        "AMS.MC",
        "CLNX.MC",
        "IDR.MC",
        "ASML.AS",
        "ADYEN.AS",
        "WKL.AS",
        "PRX.AS",
        "ASM.AS",
        "KPN.AS",
        "UMG.AS",
        "PROX.BR",
        "MELE.BR",
        "NEXI.MI",
        "INW.MI",
        "TIT.MI",
        "TEP.PA",
        "REN.AS",
        "BESI.AS",
    ],
    "Imobiliário": [
        "URW.PA",
        "VNA.DE",
        "COL.MC",
        "MRL.MC",
        "COFB.BR",
        "WDP.BR",
    ],
}


def _deduplicar_preservando_ordem(lista):
    vistos = set()
    resultado = []
    for item in lista:
        if item not in vistos:
            vistos.add(item)
            resultado.append(item)
    return resultado


setores = {
    nome: [ticker for ticker in _deduplicar_preservando_ordem(lista) if ticker in _VALID_TICKERS]
    for nome, lista in _setores_base.items()
}
